name       : konversation
version    : 1.7.5
release    : 6
source     :
    - https://cdn.download.kde.org/stable/konversation/1.7.5/src/konversation-1.7.5.tar.xz : 60bf7533062b5fc63a37105461b4776437f4e24859e8ddaed1d48c4ba1470940
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.irc
summary    : User-friendly IRC client built on the KDE Platform
description: |
    Konversation is a user-friendly Internet Relay Chat (IRC) client built on the KDE Platform.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidletime-devel
    - kitemviews-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kio-devel
    - kparts-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - solid-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-Solus-as-the-default-channel.patch
    %patch -p1 < $pkgfiles/0002-fix-build-with-qt5.13.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
