name       : konversation
version    : 1.7.7
release    : 9
source     :
    - https://cdn.download.kde.org/stable/konversation/1.7.7/src/konversation-1.7.7.tar.xz : 47ec161c1385981a8b99d28c419e88b24823dc01b68fb1623894818974c218a7
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.irc
summary    : User-friendly IRC client built on the KDE Platform
description: |
    Konversation is a user-friendly Internet Relay Chat (IRC) client built on the KDE Platform.
optimize   : lto
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidletime-devel
    - kitemviews-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kio-devel
    - kparts-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - solid-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
