name       : konversation
version    : 21.04.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/konversation-21.04.2.tar.xz : e1e63746a358bd5679309cd6c4ce15fff200cb69a36bed33b6514f2fde2fe8e9
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.irc
summary    : User-friendly IRC client built on the KDE Platform
description: |
    Konversation is a user-friendly Internet Relay Chat (IRC) client built on the KDE Platform.
optimize   : lto
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(qca2-qt5)
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kidletime-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-Repalce-Freenode-with-Libera.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
