name       : konversation
version    : 1.7.4
release    : 3
source     :
    - https://cdn.download.kde.org/stable/konversation/1.7.4/src/konversation-1.7.4.tar.xz : 17ef5b7fe816cf52aaaba9ba1b6de69412675353df4217fc889a07ca1c919978
license    :
    - GFDL-1.2
    - GPL-2.0
component  : network.irc
summary    : User-friendly IRC client built on the KDE Platform
description: |
    Konversation is a user-friendly Internet Relay Chat (IRC) client built on the KDE Platform.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidletime-devel
    - kitemviews-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kio-devel
    - kparts-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - solid-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-Solus-as-the-default-channel.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
