name       : konversation
version    : 20.12.1
release    : 12
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/konversation-20.12.1.tar.xz : 441e8924763893e5933309dd90525ed8fc37e6e7dc2eda2b1e6cab7176f4d7f4
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.irc
summary    : User-friendly IRC client built on the KDE Platform
description: |
    Konversation is a user-friendly Internet Relay Chat (IRC) client built on the KDE Platform.
optimize   : lto
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(qca2-qt5)
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kidletime-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
